### ISSUE TITLE
Error when downloading

### ISSUE THREAD

**Issue by Klaskade** [Zoeyrae/Sims4-On-Mac#12]
Hello, I get this error when trying to download the sims 4 without using crossover. What can I do? I followed Indiana tutorial and it did not work.

===> launching Sims4.app
The application /Applications/Sims4.app cannot be opened for an unexpected reason, error=Error Domain=NSCocoaErrorDomain Code=260 "The file “Sims4.app” couldn’t be opened because there is no such file." UserInfo={NSURL=file:///Applications/Sims4.app, NSFilePath=/Applications/Sims4.app, NSUnderlyingError=0x60000032c1e0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

**Comment by Zoeyrae** [comment]
please post the entire terminal output.

**Comment by Klaskade** [comment]
Last login: Mon Sep 26 16:11:04 on ttys000
/Users/sims4/Downloads/Sims4onMac-8/install.command ; exit;
sims4@Biankas-iMac ~ % /Users/sims4/Downloads/Sims4onMac-8/install.command ; exit;




















#########################################################################
################################ Sims4.app ##############################
#########################################################################

===> Downloading Wrapper Template
######################################################################### 100.0%

===> Downloading Engine
######################################################################### 100.0%

==> Downloading winetricks.
######################################################################### 100.0%

===> Creating wineprefix

===> Installing required registry keys for gshade

===> Do you own The Sims 4 through Steam or Origin?
Please Type Origin or Steam and hit Enter: Origin

===> Installing Origin, this may take a while.

===> Moving Sims4.app to your Applications folder
rsync: mkdir "/Applications/Sims4.app" failed: Permission denied (13)
rsync error: error in file IO (code 11) at /AppleInternal/Library/BuildRoots/20d6c351-ee94-11ec-bcaf-7247572f23b4/Library/Caches/com.apple.xbs/Sources/rsync/rsync/main.c(545) [receiver=2.6.9]
rsync: connection unexpectedly closed (8 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at /AppleInternal/Library/BuildRoots/20d6c351-ee94-11ec-bcaf-7247572f23b4/Library/Caches/com.apple.xbs/Sources/rsync/rsync/io.c(453) [sender=2.6.9]

===> launching Sims4.app
The application /Applications/Sims4.app cannot be opened for an unexpected reason, error=Error Domain=NSCocoaErrorDomain Code=260 "The file “Sims4.app” couldn’t be opened because there is no such file." UserInfo={NSURL=file:///Applications/Sims4.app, NSFilePath=/Applications/Sims4.app, NSUnderlyingError=0x600003d9d650 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by Zoeyrae** [comment]
It's failing to copy the .app the script create due to a permissions error, I haven't seen that before. Is this a managed laptop? (school/work issued)?
 `rsync: mkdir "/Applications/Sims4.app" failed: Permission denied (13)`

**Comment by Klaskade** [comment]
No, it’s a Desktop IMac for personal use. I have 2 user accounts one for personal and one just for Sims. My personal one is the main account manager and when the pop up to log in opens when I right click terminal it asks for permission and I put in my username and password to approve it. Once it’s complete I get the error saying it failed.

**Comment by Zoeyrae** [comment]
I just pushed a change that should fix this. it'll install it to $HOME/Applications instead.

**Comment by Klaskade** [comment]
Thank you, that fixed the problem!

**Comment by Klaskade** [comment]
Do I still need Crossover install so it can work? Shade can't see Origin installed.

**Comment by Zoeyrae** [comment]
Crap, you're running into the same problem I do when I test this script, lol. Let me change it so it doesn't default to Crossover if the .app is installed. You don't need it for Sims4 anymore though.

**Comment by Zoeyrae** [comment]
Give the gshade stuff a try now, if it detects the .app it'll not default to trying to install to Crossover anymore. Now I don't have to break the script to test the .app portion xD

**Comment by Zoeyrae** [comment]
whoops, hold on, making progress.

**Comment by Zoeyrae** [comment]
should be successfully installed now, working on it saying Sims4 isn't detected when it is.

**Comment by Klaskade** [comment]
Thank you for your help, Gshade is working now!
