### ISSUE TITLE
ghsade-shaders is gone

### ISSUE THREAD

**Issue by etheralsimss** [Zoeyrae/Sims4-On-Mac#13]
I downloaded this gshade for a second time after accidentally deleting it the first time, and when i went to redownload it everything was fine except for the gshade-shaders folder is gone and in its place is just a regular file labeled gshade-shaders. when i try to open it, it says it can't be opened because "the original cannot be found"

**Comment by Zoeyrae** [comment]
[download this](https://nextcloud.zoeyrae.dev/s/mJ5yJgaa5wkP2zq), unzip it to that folder.

**Comment by etheralsimss** [comment]
after doing that, my game will open to the point where i get the loading screen and then it will close itself

**Comment by Zoeyrae** [comment]
try opening it once again, it did that to me the first time I updated the script too but appears fine after that.

**Comment by Zoeyrae** [comment]
I haven't forgotten about you @etheralsimss, Try using the gshade script again, I was finally able to sit down and attempt a fix last night.

**Comment by etheralsimss** [comment]
i apologize, but it worked thank you so much
