### ISSUE TITLE
Same issue with gshade-shaders folder missing 

### ISSUE THREAD

**Issue by appacookies** [Zoeyrae/Sims4-On-Mac#15]
So like the other person a few days back, I have experienced the same issue with my gshade-shaders folder not being able to open or find the original. I have downloaded gshade twice and although it appears in game, everything that you'd normally see in the Home section is missing therefore my downloaded presets don't show either. Am I missing something? 

Thank You!

**Comment by Zoeyrae** [comment]
Should have been resolved with the rewrite I just merged.
