### ISSUE TITLE
Command Syntax error

### ISSUE THREAD

**Issue by xxnaixx** [Zoeyrae/Sims4-On-Mac#16]
Hi! I attempted to insert the command into the terminal but this error keeps coming up:
>/bin/bash: -c: line 38: syntax error near unexpected token `<<<'

>/bin/bash: -c: line 38: `<<<<<<< HEAD'

Is there anything I am doing wrong? I followed Indriana's tutorial up to that point. Thanks! #

**Comment by Zoeyrae** [comment]
This was a gshade error, not sims4. but it should be fixed.
